CREATE DATABASE IF NOT EXISTS prestamos_app;

USE prestamos_app;

CREATE TABLE IF NOT EXISTS objetos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion TEXT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'DISPONIBLE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prestamos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    objeto_id INT NOT NULL,
    prestamista_nombre VARCHAR(255) NOT NULL,
    prestatario_nombre VARCHAR(255) NOT NULL,
    fecha_prestamo DATETIME NOT NULL,
    fecha_devolucion_prevista DATETIME NULL,
    fecha_devolucion_real DATETIME NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    notas TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (objeto_id) REFERENCES objetos(id) ON DELETE CASCADE
);
